#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: © 2026 Marcus Rowe <undisbeliever@gmail.com>
# SPDX-License-Identifier: Zlib
#
# Copyright © 2020 Marcus Rowe <undisbeliever@gmail.com>
#
# This software is provided 'as-is', without any express or implied warranty.
# In no event will the authors be held liable for any damages arising from the
# use of this software.
#
# Permission is granted to anyone to use this software for any purpose, including
# commercial applications, and to alter it and redistribute it freely, subject to
# the following restrictions:
#
#    1. The origin of this software must not be misrepresented; you must not
#       claim that you wrote the original software. If you use this software in
#       a product, an acknowledgment in the product documentation would be
#       appreciated but is not required.
#
#    2. Altered source versions must be plainly marked as such, and must not be
#       misrepresented as being the original software.
#
#    3. This notice may not be removed or altered from any source distribution.

from _file_parsers import read_resources_txt, Resources

import argparse
from io import StringIO


def generate_header(resources: Resources) -> str:
    with StringIO() as out:
        out.write("""// autogenerated by gen-enum-header.py

#ifndef H__GEN_ENUMS_H_
#define H__GEN_ENUMS_H_


""")

        out.write(f"#define N_RESOURCES {len(resources)}\n")
        out.write("\n")

        for i, r in enumerate(resources.resources):
            out.write(f"#define RES_{r.name} {i}\n")

        out.write("""
#endif
""")

        return out.getvalue()


def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--output", required=True, help="C header output file")
    parser.add_argument(
        "resources_filename", action="store", help="resources.txt filename"
    )

    args = parser.parse_args()

    return args


def main():
    args = parse_arguments()

    resources = read_resources_txt(args.resources_filename)

    out = generate_header(resources)

    with open(args.output, "w") as fp:
        fp.write(out)


if __name__ == "__main__":
    main()
